services:
  - type: web
    name: esports-graph-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: COGNO_URI
        sync: false
      - key: COGNO_USER
        sync: false
      - key: COGNO_PASSWORD
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 4000
